import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import {
  Sparkles,
  ArrowRight,
  Bot,
  CheckCircle2,
  Clock,
  Award,
  TrendingUp,
  BarChart3,
  BookOpen,
  Layers,
  ShieldCheck,
  Zap,
  GraduationCap,
  Users,
  ChevronDown,
  Play,
  Flame,
  Check,
  School,
  FileText,
  Star,
  Globe2,
  Cpu,
  ArrowUpRight,
  HelpCircle,
  BrainCircuit,
  Laptop,
} from 'lucide-react';
import { useApp } from '../context/AppContext';
import { useAuth } from '../context/AuthContext';

export const LandingView: React.FC = () => {
  const {
    setCurrentView,
    setStudentTab,
    setSelectedSubject,
    subjects,
    startMockTest,
    setIsAiTutorOpen,
    setIsProModalOpen,
  } = useApp();
  const { openAuthModal } = useAuth();

  // Pricing Toggle (Monthly vs Yearly)
  const [billingCycle, setBillingCycle] = useState<'monthly' | 'yearly'>('yearly');

  // FAQ Accordion Active Item
  const [activeFaq, setActiveFaq] = useState<number | null>(0);

  // AI Tutor Showcase Active Tab
  const [showcaseTab, setShowcaseTab] = useState<'math' | 'science' | 'kannada' | 'tips'>('math');

  const faqs = [
    {
      q: 'Can I cancel anytime?',
      a: 'Yes, cancel anytime with one click in your account settings. There are no cancellation fees, no hidden charges, and you retain access until the end of your billing cycle.',
    },
    {
      q: 'Is there a free trial?',
      a: 'Yes! Every student starts with a 10-day full access free trial including AI Tutor, daily quizzes, PDF analysis, file uploads, teacher classes, and official quizzes with no credit card required.',
    },
    {
      q: 'Can teachers use Pro?',
      a: 'Yes! Teachers on Pro and Ultra get full access to the CBT Exam Builder, multi-format question banks, real-time grading, and automated Student Certificate Creator with custom institution stamps.',
    },
    {
      q: 'Are certificates valid?',
      a: 'Yes! Every certificate generated by EasiaLearn contains a cryptographic QR code, unique Verification ID (e.g. EA-CERT-84920), score breakdown, and is officially recognized for academic portfolios.',
    },
    {
      q: 'Does EasiaLearn follow the official Karnataka SSLC & KSEAB syllabus?',
      a: 'Yes, 100%. Our curriculum, mock tests, and question banks are strictly mapped to the Karnataka State Examination & Assessment Board (KSEAB) blueprints, NCERT standards, and previous 10 years of solved question papers.',
    },
    {
      q: 'What languages does the AI Tutor support?',
      a: 'EasiaLearn AI Tutor is fully fluent in Kannada (ಕನ್ನಡ), English, Urdu, and Hindi. You can ask questions in Kannada script, Roman Kannada ("Nanna doubt enu..."), or English and receive clear, step-by-step explanations.',
    },
    {
      q: 'How does the Board Exam Score Predictor work?',
      a: 'Our AI engine analyzes your accuracy across practice tests, response times, weak-chapter performance, and past state board distributions to calculate an estimated board score with over 94% historical accuracy.',
    },
    {
      q: 'What are EasiaCoins and how do I earn them?',
      a: 'EasiaCoins are our gamified reward system. You earn coins by maintaining daily study streaks, scoring above 80% on mock exams, completing chapter lessons, and unlocking official achievement badges.',
    },
  ];

  const showcaseContent = {
    math: {
      userQuestion: 'How do I find the nature of roots for 2x² - 4x + 3 = 0?',
      response:
        'To find the nature of roots, we calculate the Discriminant (Δ = b² - 4ac):\n1. Identify coefficients: a = 2, b = -4, c = 3.\n2. Compute Δ: (-4)² - 4(2)(3) = 16 - 24 = -8.\n3. Conclusion: Since Δ < 0, this equation has no real roots (the roots are imaginary / complex).',
      tag: 'SSLC Board Math • High Weightage',
    },
    science: {
      userQuestion: 'Explain the difference between concave and convex lenses with sign convention.',
      response:
        'Key Optical Differences:\n• Concave Lens: Thinner in the middle, diverging lens. Focal length (f) is always negative (-).\n• Convex Lens: Thicker in the middle, converging lens. Focal length (f) is positive (+).\nRemember for 10th Board: The Lens Formula is 1/f = 1/v - 1/u.',
      tag: 'Physics • Ray Optics',
    },
    kannada: {
      userQuestion: 'ಸಮಾಂತರ ಶ್ರೇಢಿಯ (AP) n ನೇ ಪದವನ್ನು ಕಂಡುಹಿಡಿಯುವ ಸೂತ್ರ ಯಾವುದು?',
      response:
        'ಸಮಾಂತರ ಶ್ರೇಢಿಯ n ನೇ ಪದವನ್ನು ಕಂಡುಹಿಡಿಯುವ ಮುಖ್ಯ ಸೂತ್ರ:\nan = a + (n - 1)d\n• a = ಮೊದಲ ಪದ (First term)\n• d = ಸಾಮಾನ್ಯ ವ್ಯತ್ಯಾಸ (Common difference)\n• n = ಪದಗಳ ಸಂಖ್ಯೆ (Number of terms)',
      tag: 'ಕನ್ನಡ ಮಾಧ್ಯಮ • 10ನೇ ತರಗತಿ',
    },
    tips: {
      userQuestion: 'What are the top 3 scoring tips for the 2026 Karnataka SSLC Board Exam?',
      response:
        'Top 3 Board Strategies:\n1. Master 4-mark theorems first (Thales Theorem, Pythagoras Theorem).\n2. Practice neat ray diagrams with arrows in Physics.\n3. Solve at least 3 timed CBT Mock Tests to eliminate negative time pressure.',
      tag: 'Exam Strategy • State Rankers',
    },
  };

  return (
    <div className="min-h-screen bg-[#F8FAFC] text-[#111111] overflow-x-hidden selection:bg-[#2952CC] selection:text-white">
      {/* ============================================================ */}
      {/* SECTION 1 — PREMIUM HERO */}
      {/* ============================================================ */}
      <section className="relative pt-8 pb-16 md:pt-14 md:pb-24 px-4 sm:px-6 lg:px-8 max-w-[1280px] mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-8 items-center">
          {/* Left Column */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="lg:col-span-7 space-y-6 text-left"
          >
            {/* Pill Badge */}
            <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full bg-[#EAF2FF] border border-blue-100 text-[#2952CC] text-xs sm:text-sm font-semibold shadow-xs">
              <Sparkles className="w-4 h-4 text-[#2952CC]" />
              <span>India&apos;s Smart Learning Platform</span>
            </div>

            {/* Headline */}
            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-[#111111] leading-[1.15]">
              Learn Easier. <br />
              <span className="text-[#2952CC]">Score Higher.</span>
            </h1>

            {/* Description */}
            <p className="text-base sm:text-lg text-[#475569] max-w-xl leading-relaxed">
              Master your Karnataka SSLC and board syllabus with 24/7 multilingual AI tutoring, real
              CBT mock test simulations, personalized score prediction, and verified credentials.
            </p>

            {/* Primary & Secondary CTAs */}
            <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3.5 pt-2">
              <button
                id="hero-start-free-btn"
                onClick={() => openAuthModal('signup')}
                className="inline-flex items-center justify-center gap-2 px-7 py-3.5 rounded-2xl bg-[#2952CC] text-white font-bold text-sm sm:text-base hover:bg-blue-800 transition-all shadow-md shadow-blue-600/20 active:scale-[0.98]"
              >
                Start Learning Free
                <ArrowRight className="w-4 h-4" />
              </button>

              <button
                id="hero-demo-btn"
                onClick={() => setIsAiTutorOpen(true)}
                className="inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-2xl bg-white border border-[#E5E7EB] text-[#111111] font-semibold text-sm sm:text-base hover:bg-slate-50 hover:border-slate-300 transition-all shadow-xs"
              >
                <Bot className="w-4 h-4 text-[#2952CC]" />
                Try AI Tutor Demo
              </button>
            </div>

            {/* Trust Badges Row */}
            <div className="pt-2 flex flex-wrap items-center gap-y-2 gap-x-5 text-xs text-[#475569] font-medium">
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                No credit card required
              </span>
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                Instant access
              </span>
              <span className="flex items-center gap-1.5">
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                100% Free Starter Tier
              </span>
            </div>
          </motion.div>

          {/* Right Column: 3D-feel Interactive Mockup Card */}
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.7, delay: 0.15 }}
            className="lg:col-span-5 relative"
          >
            {/* Background Ambient Glow */}
            <div className="absolute -inset-4 bg-gradient-to-tr from-blue-200/40 via-[#4F7DF3]/20 to-indigo-200/40 rounded-[32px] blur-2xl -z-10" />

            {/* Main Interactive Card */}
            <div className="bg-white rounded-[24px] border border-[#E5E7EB] shadow-xl p-6 relative space-y-5">
              {/* Header Bar */}
              <div className="flex items-center justify-between border-b border-slate-100 pb-4">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#2952CC] to-[#4F7DF3] flex items-center justify-center text-white font-bold text-sm shadow-xs">
                    EA
                  </div>
                  <div>
                    <h3 className="font-bold text-sm text-[#111111]">Student Study Center</h3>
                    <p className="text-[11px] text-[#475569]">Karnataka SSLC Board 2026</p>
                  </div>
                </div>

                <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
                  Live Sync
                </span>
              </div>

              {/* Score Predictor Gauge */}
              <div className="p-4 rounded-2xl bg-[#F8FAFC] border border-slate-200 space-y-2">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-semibold text-[#475569]">Projected Board Score</span>
                  <span className="font-extrabold text-[#2952CC] text-sm">94.8% (Distinction)</span>
                </div>
                <div className="w-full bg-slate-200 h-2.5 rounded-full overflow-hidden">
                  <div className="bg-[#2952CC] h-full rounded-full transition-all duration-1000" style={{ width: '94.8%' }} />
                </div>
                <div className="flex justify-between text-[10px] text-slate-400">
                  <span>Pass (35%)</span>
                  <span>First Class (60%)</span>
                  <span className="text-[#2952CC] font-bold">Top 1% Ranker</span>
                </div>
              </div>

              {/* Simulated AI Tutor Chat Box */}
              <div className="space-y-3">
                <div className="flex items-start gap-2.5">
                  <div className="w-7 h-7 rounded-full bg-slate-100 flex items-center justify-center text-xs font-bold text-slate-600 shrink-0">
                    You
                  </div>
                  <div className="bg-slate-100 rounded-2xl rounded-tl-xs px-3.5 py-2 text-xs text-[#111111] max-w-[85%]">
                    Can you explain Quadratic Formula roots Δ in Kannada and English?
                  </div>
                </div>

                <div className="flex items-start gap-2.5">
                  <div className="w-7 h-7 rounded-full bg-[#2952CC] flex items-center justify-center text-xs font-bold text-white shrink-0">
                    <Bot className="w-4 h-4" />
                  </div>
                  <div className="bg-[#EAF2FF] border border-blue-100 rounded-2xl rounded-tl-xs p-3 text-xs text-[#111111] space-y-1.5 max-w-[90%] shadow-xs">
                    <div className="flex items-center justify-between text-[10px] text-[#2952CC] font-bold">
                      <span>EasiaLearn AI Tutor</span>
                      <span>Just now</span>
                    </div>
                    <p className="font-mono text-[11px] font-bold text-[#2952CC] bg-white px-2 py-1 rounded border border-blue-200">
                      Δ = b² - 4ac (ಮೂಲಗಳ ಸ್ವಭಾವ)
                    </p>
                    <p className="text-[11px] text-[#475569] leading-snug">
                      • Δ &gt; 0: Two distinct real roots (ಎರಡು ಭಿನ್ನ ನೈಜ ಮೂಲಗಳು)<br />
                      • Δ = 0: Equal real roots (ಸಮಾನ ನೈಜ ಮೂಲಗಳು)<br />
                      • Δ &lt; 0: No real roots (ಯಾವುದೇ ನೈಜ ಮೂಲಗಳಿಲ್ಲ)
                    </p>
                  </div>
                </div>
              </div>

              {/* Floating Badges */}
              <div className="pt-2 flex flex-wrap gap-2">
                <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-amber-50 text-amber-800 border border-amber-200 text-xs font-semibold shadow-xs">
                  <Flame className="w-3.5 h-3.5 text-amber-500 fill-amber-500" />
                  <span>18-Day Streak Active</span>
                </div>
                <div className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-purple-50 text-purple-800 border border-purple-200 text-xs font-semibold shadow-xs">
                  <Award className="w-3.5 h-3.5 text-purple-600" />
                  <span>State Rank #14</span>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 2 — TRUSTED BY THOUSANDS / KEY METRICS */}
      {/* ============================================================ */}
      <section className="py-12 bg-white border-y border-[#E5E7EB]">
        <div className="max-w-[1280px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto mb-8">
            <p className="text-xs uppercase tracking-widest font-bold text-[#2952CC]">Proven Outcomes</p>
            <h2 className="text-xl sm:text-2xl font-bold text-[#111111] mt-1">
              Trusted by 50,000+ Students & 1,200+ Institutions Across Karnataka
            </h2>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            <div className="p-4 rounded-2xl bg-[#F8FAFC] border border-slate-100">
              <p className="text-3xl sm:text-4xl font-extrabold text-[#2952CC]">50,000+</p>
              <p className="text-xs sm:text-sm font-semibold text-[#111111] mt-1">Active Learners</p>
              <p className="text-[11px] text-[#475569]">SSLC & PUC Students</p>
            </div>

            <div className="p-4 rounded-2xl bg-[#F8FAFC] border border-slate-100">
              <p className="text-3xl sm:text-4xl font-extrabold text-[#2952CC]">94.6%</p>
              <p className="text-xs sm:text-sm font-semibold text-[#111111] mt-1">Score Improvement</p>
              <p className="text-[11px] text-[#475569]">Average post-CBT gains</p>
            </div>

            <div className="p-4 rounded-2xl bg-[#F8FAFC] border border-slate-100">
              <p className="text-3xl sm:text-4xl font-extrabold text-[#2952CC]">1,200+</p>
              <p className="text-xs sm:text-sm font-semibold text-[#111111] mt-1">Karnataka Schools</p>
              <p className="text-[11px] text-[#475569]">Using EasiaLearn Campus</p>
            </div>

            <div className="p-4 rounded-2xl bg-[#F8FAFC] border border-slate-100">
              <p className="text-3xl sm:text-4xl font-extrabold text-[#2952CC]">4.9 / 5</p>
              <p className="text-xs sm:text-sm font-semibold text-[#111111] mt-1">User Satisfaction</p>
              <p className="text-[11px] text-[#475569]">From 12,000+ reviews</p>
            </div>
          </div>

          {/* Supported Boards & Mediums Banner */}
          <div className="mt-8 pt-6 border-t border-slate-100 flex flex-wrap items-center justify-center gap-6 text-xs font-semibold text-[#475569]">
            <span className="text-[#111111] font-bold">Curriculum Standards:</span>
            <span className="px-3 py-1 rounded-full bg-slate-100">Karnataka KSEAB Board</span>
            <span className="px-3 py-1 rounded-full bg-slate-100">NCERT Standards</span>
            <span className="px-3 py-1 rounded-full bg-slate-100">Kannada Medium (ಕನ್ನಡ)</span>
            <span className="px-3 py-1 rounded-full bg-slate-100">English Medium</span>
            <span className="px-3 py-1 rounded-full bg-slate-100">Urdu Medium</span>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 3 — HOW EASIALEARN WORKS (3 STEPS) */}
      {/* ============================================================ */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 max-w-[1280px] mx-auto">
        <div className="text-center max-w-2xl mx-auto space-y-3 mb-14">
          <span className="text-xs uppercase tracking-widest font-bold text-[#2952CC]">Simple 3-Step Journey</span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-[#111111]">How EasiaLearn Accelerates Your Scores</h2>
          <p className="text-sm sm:text-base text-[#475569]">
            From identifying chapter knowledge gaps to writing full-length state board CBT exams with confidence.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
          {/* Step 1 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-8 shadow-sm hover:shadow-md transition-all space-y-5 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] font-extrabold text-xl flex items-center justify-center">
                01
              </div>
              <h3 className="text-xl font-bold text-[#111111]">Select Class & Medium</h3>
              <p className="text-sm text-[#475569] leading-relaxed">
                Choose your specific target examination: 10th SSLC, 9th Foundation, or 1st/2nd PUC in English, Kannada, or Urdu medium.
              </p>
            </div>
            <div className="p-3 bg-[#F8FAFC] rounded-xl border border-slate-100 text-xs font-semibold text-[#2952CC] flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>Full KSEAB Chapter Syllabus Included</span>
            </div>
          </div>

          {/* Step 2 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-8 shadow-sm hover:shadow-md transition-all space-y-5 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] font-extrabold text-xl flex items-center justify-center">
                02
              </div>
              <h3 className="text-xl font-bold text-[#111111]">Learn with AI & Video Notes</h3>
              <p className="text-sm text-[#475569] leading-relaxed">
                Ask doubts 24/7 in your native tongue, get instant step-by-step math solutions, and study concise board revision summaries.
              </p>
            </div>
            <div className="p-3 bg-[#F8FAFC] rounded-xl border border-slate-100 text-xs font-semibold text-[#2952CC] flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>Export Solved PDFs & Flashcards</span>
            </div>
          </div>

          {/* Step 3 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-8 shadow-sm hover:shadow-md transition-all space-y-5 flex flex-col justify-between">
            <div className="space-y-4">
              <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] font-extrabold text-xl flex items-center justify-center">
                03
              </div>
              <h3 className="text-xl font-bold text-[#111111]">Simulate Real CBT Mock Exams</h3>
              <p className="text-sm text-[#475569] leading-relaxed">
                Practice with authentic question palettes, countdown timers, and instant diagnostics that predict your exact board percentile.
              </p>
            </div>
            <div className="p-3 bg-[#F8FAFC] rounded-xl border border-slate-100 text-xs font-semibold text-[#2952CC] flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>Earn Verifiable Certificates</span>
            </div>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 4 — AI TUTOR SHOWCASE (INTERACTIVE DEMO) */}
      {/* ============================================================ */}
      <section className="py-16 bg-white border-y border-[#E5E7EB]">
        <div className="max-w-[1280px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-center">
            {/* Left Content */}
            <div className="lg:col-span-5 space-y-6 text-left">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#EAF2FF] text-[#2952CC] text-xs font-bold">
                <BrainCircuit className="w-4 h-4" />
                <span>Next-Gen Academic Engine</span>
              </div>

              <h2 className="text-3xl sm:text-4xl font-extrabold text-[#111111] leading-tight">
                Meet Your 24/7 Personal Board Exam Mentor
              </h2>

              <p className="text-sm sm:text-base text-[#475569] leading-relaxed">
                No more waiting until the next school day to get answers. EasiaLearn AI Tutor provides instant,
                patient, and culturally fluent explanations in Kannada, English, and Urdu with formulas and diagrams.
              </p>

              {/* Feature Highlights */}
              <div className="space-y-3 pt-2">
                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center shrink-0 mt-0.5">
                    <Check className="w-3 h-3 stroke-[3]" />
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-[#111111]">Multilingual Fluency</h4>
                    <p className="text-xs text-[#475569]">Fluently understands and replies in Kannada, English, Urdu, and Hindi.</p>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center shrink-0 mt-0.5">
                    <Check className="w-3 h-3 stroke-[3]" />
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-[#111111]">Step-by-Step Math & Science Derivations</h4>
                    <p className="text-xs text-[#475569]">Never skips intermediate steps so you know exactly how marks are earned.</p>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center shrink-0 mt-0.5">
                    <Check className="w-3 h-3 stroke-[3]" />
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-[#111111]">Instant Document & Flashcard Export</h4>
                    <p className="text-xs text-[#475569]">Generate revision PDFs, formulas, and presentations in one click.</p>
                  </div>
                </div>
              </div>

              <div className="pt-2">
                <button
                  id="showcase-launch-tutor-btn"
                  onClick={() => setIsAiTutorOpen(true)}
                  className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl bg-[#2952CC] text-white font-bold text-sm hover:bg-blue-800 transition-all shadow-md shadow-blue-600/20"
                >
                  <Bot className="w-4 h-4" />
                  Launch Interactive AI Tutor
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>

            {/* Right Interactive Chat Preview */}
            <div className="lg:col-span-7">
              <div className="bg-[#F8FAFC] rounded-[24px] border border-[#E5E7EB] p-6 shadow-lg space-y-4">
                {/* Tabs */}
                <div className="flex flex-wrap gap-2 border-b border-slate-200 pb-3">
                  <button
                    onClick={() => setShowcaseTab('math')}
                    className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                      showcaseTab === 'math'
                        ? 'bg-[#2952CC] text-white shadow-xs'
                        : 'bg-white text-[#475569] hover:text-[#111111] border border-slate-200'
                    }`}
                  >
                    Mathematics Solver
                  </button>
                  <button
                    onClick={() => setShowcaseTab('science')}
                    className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                      showcaseTab === 'science'
                        ? 'bg-[#2952CC] text-white shadow-xs'
                        : 'bg-white text-[#475569] hover:text-[#111111] border border-slate-200'
                    }`}
                  >
                    Physics & Chemistry
                  </button>
                  <button
                    onClick={() => setShowcaseTab('kannada')}
                    className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                      showcaseTab === 'kannada'
                        ? 'bg-[#2952CC] text-white shadow-xs'
                        : 'bg-white text-[#475569] hover:text-[#111111] border border-slate-200'
                    }`}
                  >
                    ಕನ್ನಡ ಮಾಧ್ಯಮ (Kannada)
                  </button>
                  <button
                    onClick={() => setShowcaseTab('tips')}
                    className={`px-3.5 py-1.5 rounded-xl text-xs font-bold transition-all ${
                      showcaseTab === 'tips'
                        ? 'bg-[#2952CC] text-white shadow-xs'
                        : 'bg-white text-[#475569] hover:text-[#111111] border border-slate-200'
                    }`}
                  >
                    Board Exam Strategy
                  </button>
                </div>

                {/* Question & Answer Box */}
                <div className="space-y-3 pt-2">
                  <div className="bg-white p-4 rounded-2xl border border-slate-200 space-y-1">
                    <span className="text-[11px] font-bold text-[#475569] uppercase tracking-wider">Student Query</span>
                    <p className="text-sm font-semibold text-[#111111]">{showcaseContent[showcaseTab].userQuestion}</p>
                  </div>

                  <div className="bg-white p-5 rounded-2xl border border-blue-200 space-y-3 shadow-xs">
                    <div className="flex items-center justify-between border-b border-slate-100 pb-2">
                      <div className="flex items-center gap-2">
                        <div className="w-6 h-6 rounded-lg bg-[#2952CC] text-white flex items-center justify-center">
                          <Bot className="w-3.5 h-3.5" />
                        </div>
                        <span className="text-xs font-bold text-[#111111]">EasiaLearn Academic Tutor</span>
                      </div>
                      <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-blue-50 text-[#2952CC]">
                        {showcaseContent[showcaseTab].tag}
                      </span>
                    </div>

                    <div className="text-xs sm:text-sm text-[#111111] leading-relaxed whitespace-pre-line">
                      {showcaseContent[showcaseTab].response}
                    </div>

                    <div className="pt-2 border-t border-slate-100 flex items-center justify-between text-xs text-[#475569]">
                      <span>Instant doubt verification</span>
                      <button
                        onClick={() => setIsAiTutorOpen(true)}
                        className="text-[#2952CC] font-bold hover:underline inline-flex items-center gap-1"
                      >
                        Ask custom question <ArrowRight className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 5 — EVERYTHING IN ONE PLATFORM (6 FEATURE CARDS) */}
      {/* ============================================================ */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 max-w-[1280px] mx-auto">
        <div className="text-center max-w-2xl mx-auto space-y-3 mb-14">
          <span className="text-xs uppercase tracking-widest font-bold text-[#2952CC]">All-In-One Toolkit</span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-[#111111]">
            Everything You Need to Rank at the Top
          </h2>
          <p className="text-sm sm:text-base text-[#475569]">
            A comprehensive suite of study, practice, and testing tools built specifically for state and national curricula.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Card 1 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm hover:shadow-md hover:border-[#2952CC]/40 transition-all space-y-4 group">
            <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] flex items-center justify-center group-hover:scale-105 transition-transform">
              <Bot className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-[#111111]">AI 24/7 Personal Tutor</h3>
            <p className="text-xs sm:text-sm text-[#475569] leading-relaxed">
              Step-by-step homework help, conceptual breakdowns, and instant problem-solving in English, Kannada, and Urdu.
            </p>
          </div>

          {/* Card 2 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm hover:shadow-md hover:border-[#2952CC]/40 transition-all space-y-4 group">
            <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] flex items-center justify-center group-hover:scale-105 transition-transform">
              <Laptop className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-[#111111]">State CBT Mock Exams</h3>
            <p className="text-xs sm:text-sm text-[#475569] leading-relaxed">
              Real examination timing, question palettes, negative marking, and proctored environments to conquer exam anxiety.
            </p>
          </div>

          {/* Card 3 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm hover:shadow-md hover:border-[#2952CC]/40 transition-all space-y-4 group">
            <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] flex items-center justify-center group-hover:scale-105 transition-transform">
              <BarChart3 className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-[#111111]">Smart Score Predictor</h3>
            <p className="text-xs sm:text-sm text-[#475569] leading-relaxed">
              Real-time analytics highlight weak chapters, measure topic accuracy, and project your final state board percentage.
            </p>
          </div>

          {/* Card 4 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm hover:shadow-md hover:border-[#2952CC]/40 transition-all space-y-4 group">
            <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] flex items-center justify-center group-hover:scale-105 transition-transform">
              <Flame className="w-6 h-6 text-amber-500" />
            </div>
            <h3 className="text-lg font-bold text-[#111111]">Daily Streaks & EasiaCoins</h3>
            <p className="text-xs sm:text-sm text-[#475569] leading-relaxed">
              Gamified habit building keeps you consistent. Earn badges, level up your avatar, and unlock premium practice test archives.
            </p>
          </div>

          {/* Card 5 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm hover:shadow-md hover:border-[#2952CC]/40 transition-all space-y-4 group">
            <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] flex items-center justify-center group-hover:scale-105 transition-transform">
              <Layers className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-[#111111]">High-Yield Flashcards</h3>
            <p className="text-xs sm:text-sm text-[#475569] leading-relaxed">
              Spaced repetition flashcards designed for quick memory recall of formulas, scientific laws, definitions, and dates.
            </p>
          </div>

          {/* Card 6 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm hover:shadow-md hover:border-[#2952CC]/40 transition-all space-y-4 group">
            <div className="w-12 h-12 rounded-2xl bg-[#EAF2FF] text-[#2952CC] flex items-center justify-center group-hover:scale-105 transition-transform">
              <Award className="w-6 h-6" />
            </div>
            <h3 className="text-lg font-bold text-[#111111]">Verifiable Board Certificates</h3>
            <p className="text-xs sm:text-sm text-[#475569] leading-relaxed">
              Top percentile scores earn cryptographic certificates with QR verification for academic portfolios and school recognition.
            </p>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* ============================================================ */}
      {/* SECTION 6 — CHOOSE YOUR LEARNING PLAN (FREE, PRO, ULTRA, ANNUAL) */}
      {/* ============================================================ */}
      <section id="pricing-section" className="py-20 bg-white border-y border-[#E5E7EB]">
        <div className="max-w-[1280px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center max-w-2xl mx-auto space-y-3 mb-12">
            <span className="text-xs uppercase tracking-widest font-bold text-[#2952CC]">Flexible Subscriptions</span>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#111111]">
              Choose Your Learning Plan
            </h2>
            <p className="text-sm sm:text-base text-[#475569]">
              Transparent pricing with no hidden charges. Cancel anytime or upgrade for unlimited AI tutoring, CBT exams, and verified credentials.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 items-stretch max-w-6xl mx-auto">
            {/* 1. FREE TRIAL */}
            <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-8 shadow-sm flex flex-col justify-between space-y-6 hover:border-slate-300 transition-all">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold px-3 py-1 rounded-full bg-slate-100 text-slate-700">
                    Starter
                  </span>
                  <span className="text-xs font-semibold text-emerald-600">10 Days Trial</span>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-[#111111]">Free Trial</h3>
                  <p className="text-xs text-[#475569] mt-1">Explore core features with zero commitment</p>
                </div>

                <div className="pt-2">
                  <span className="text-4xl font-extrabold text-[#111111]">₹0</span>
                  <span className="text-xs text-[#475569] ml-1.5 font-medium">/ 10 Days</span>
                </div>

                <ul className="space-y-3 text-xs text-[#475569] pt-2 border-t border-slate-100">
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>AI Tutor (5 queries / day)</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>Daily Quizzes</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>PDF Analysis</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>5 File Uploads</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>Basic Chat History</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>Join Teacher Classes</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-emerald-600 shrink-0" />
                    <span>Participate in Official Quizzes</span>
                  </li>
                </ul>
              </div>

              <button
                id="plan-free-btn"
                onClick={() => openAuthModal('signup')}
                className="w-full py-3.5 rounded-2xl border border-slate-300 text-[#111111] font-bold text-xs sm:text-sm hover:bg-slate-50 transition-all shadow-xs"
              >
                Start Free Trial
              </button>
            </div>

            {/* 2. PRO (MOST POPULAR) */}
            <div className="bg-gradient-to-b from-blue-50/70 via-white to-white rounded-[24px] border-2 border-[#2952CC] p-8 shadow-xl flex flex-col justify-between space-y-6 relative hover:shadow-2xl transition-all">
              <div className="absolute -top-3.5 left-1/2 -translate-x-1/2 bg-[#2952CC] text-white text-[11px] font-bold px-3.5 py-1 rounded-full uppercase tracking-wider shadow-sm flex items-center gap-1">
                <Sparkles className="w-3 h-3 text-amber-300" />
                MOST POPULAR
              </div>

              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold px-3 py-1 rounded-full bg-blue-100 text-[#2952CC]">
                    Student Choice
                  </span>
                  <span className="text-xs font-semibold text-[#2952CC]">Monthly</span>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-[#111111]">Pro</h3>
                  <p className="text-xs text-[#475569] mt-1">Full state board mastery & certificate unlock</p>
                </div>

                <div className="pt-2">
                  <span className="text-4xl font-extrabold text-[#2952CC]">₹999</span>
                  <span className="text-xs text-[#475569] ml-1.5 font-medium">/ Month</span>
                </div>

                <ul className="space-y-3 text-xs text-[#111111] pt-2 border-t border-blue-100">
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Unlimited AI Tutor</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Unlimited PDF Generation</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Excel (.xlsx) Generation</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Word & PPT Generation</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>20+ File Uploads Per Chat</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Teacher Quiz Access</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Teacher Exam Access</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Certificate Generation</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Advanced Analytics</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Priority AI Responses</span>
                  </li>
                  <li className="flex items-center gap-2 font-medium">
                    <Check className="w-4 h-4 text-[#2952CC] stroke-[3] shrink-0" />
                    <span>Unlimited Chat History</span>
                  </li>
                </ul>
              </div>

              <button
                id="plan-pro-btn"
                onClick={() => setIsProModalOpen(true)}
                className="w-full py-3.5 rounded-2xl bg-[#2952CC] text-white font-bold text-xs sm:text-sm hover:bg-blue-800 transition-all shadow-md shadow-blue-600/25"
              >
                Upgrade to Pro
              </button>
            </div>

            {/* 3. ULTRA (PRO MAX) */}
            <div className="bg-[#0B132B] text-white rounded-[24px] border border-slate-800 p-8 shadow-2xl flex flex-col justify-between space-y-6 relative hover:border-slate-700 transition-all">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold px-3 py-1 rounded-full bg-amber-400/20 text-amber-300 border border-amber-400/30">
                    Pro Max
                  </span>
                  <span className="text-xs font-semibold text-slate-400">Monthly</span>
                </div>
                <div>
                  <h3 className="text-2xl font-bold text-white">Ultra</h3>
                  <p className="text-xs text-slate-300 mt-1">Research tools, institution power & team sync</p>
                </div>

                <div className="pt-2">
                  <span className="text-4xl font-extrabold text-white">₹3,999</span>
                  <span className="text-xs text-slate-400 ml-1.5 font-medium">/ Month</span>
                </div>

                <ul className="space-y-3 text-xs text-slate-300 pt-2 border-t border-slate-800">
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Unlimited File Uploads</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>100+ Files Per Workspace</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Institution Collaboration</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>AI Research Mode</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Large Document Analysis</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Premium Templates</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Unlimited Certificates</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Advanced Exam Analytics</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Team Collaboration</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <Check className="w-4 h-4 text-amber-400 shrink-0" />
                    <span>Priority Support</span>
                  </li>
                </ul>
              </div>

              <button
                id="plan-ultra-btn"
                onClick={() => setIsProModalOpen(true)}
                className="w-full py-3.5 rounded-2xl bg-white text-[#0B132B] font-bold text-xs sm:text-sm hover:bg-slate-100 transition-all shadow-md"
              >
                Go Ultra
              </button>
            </div>
          </div>

          {/* 4. ANNUAL PLAN PROMO BANNER */}
          <div className="mt-10 max-w-6xl mx-auto rounded-[24px] p-6 sm:p-8 bg-gradient-to-r from-[#2952CC] via-[#3B62E3] to-[#4F7DF3] text-white shadow-xl flex flex-col sm:flex-row items-center justify-between gap-6">
            <div className="space-y-2 text-center sm:text-left">
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/20 text-xs font-bold tracking-wide uppercase">
                <Sparkles className="w-3.5 h-3.5 text-amber-300" />
                Annual Plan • Save 40%
              </div>
              <h3 className="text-2xl sm:text-3xl font-extrabold">Full Academic Year: ₹9,999 / Year</h3>
              <p className="text-xs sm:text-sm text-blue-100 max-w-xl">
                Includes all Ultra features, unlimited AI tutor, unlimited mock test sessions, and unlimited verified certificates for an entire 365-day academic calendar.
              </p>
            </div>
            <button
              id="plan-annual-btn"
              onClick={() => setIsProModalOpen(true)}
              className="px-8 py-3.5 rounded-2xl bg-white text-[#2952CC] font-extrabold text-sm sm:text-base hover:bg-blue-50 transition-all shadow-lg shrink-0"
            >
              Get Annual Plan
            </button>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 7 — TESTIMONIALS (STUDENTS & EDUCATORS) */}
      {/* ============================================================ */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 max-w-[1280px] mx-auto">
        <div className="text-center max-w-2xl mx-auto space-y-3 mb-14">
          <span className="text-xs uppercase tracking-widest font-bold text-[#2952CC]">Verified Reviews</span>
          <h2 className="text-3xl sm:text-4xl font-extrabold text-[#111111]">
            Real Stories from Real Board Toppers
          </h2>
          <p className="text-sm sm:text-base text-[#475569]">
            See how students and principals across Karnataka transformed their performance with EasiaLearn.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {/* Review 1 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm space-y-5 flex flex-col justify-between">
            <div className="space-y-3">
              <div className="flex text-amber-400 gap-1">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className="w-4 h-4 fill-amber-400" />
                ))}
              </div>
              <p className="text-xs sm:text-sm text-[#111111] leading-relaxed italic">
                &ldquo;EasiaLearn transformed how I approached Math and Science for SSLC. Asking the AI Tutor to explain
                theorems in simple Kannada cleared my confusion in minutes! I scored 96.8% in the board finals.&rdquo;
              </p>
            </div>

            <div className="flex items-center gap-3 pt-3 border-t border-slate-100">
              <div className="w-10 h-10 rounded-full bg-[#EAF2FF] text-[#2952CC] font-bold text-sm flex items-center justify-center">
                AR
              </div>
              <div>
                <h4 className="text-sm font-bold text-[#111111]">Ananya Rao</h4>
                <p className="text-[11px] text-[#475569]">10th SSLC • 96.8% Board Score (Bengaluru)</p>
              </div>
            </div>
          </div>

          {/* Review 2 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm space-y-5 flex flex-col justify-between">
            <div className="space-y-3">
              <div className="flex text-amber-400 gap-1">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className="w-4 h-4 fill-amber-400" />
                ))}
              </div>
              <p className="text-xs sm:text-sm text-[#111111] leading-relaxed italic">
                &ldquo;The CBT Mock tests give you the exact timer and pressure of the state exam. Seeing my projected
                board score jump from 78% to 92% gave me unstoppable confidence.&rdquo;
              </p>
            </div>

            <div className="flex items-center gap-3 pt-3 border-t border-slate-100">
              <div className="w-10 h-10 rounded-full bg-emerald-50 text-emerald-700 font-bold text-sm flex items-center justify-center">
                MZ
              </div>
              <div>
                <h4 className="text-sm font-bold text-[#111111]">Mohammed Zaid</h4>
                <p className="text-[11px] text-[#475569]">PUC Learner • State Rank #42 (Mysuru)</p>
              </div>
            </div>
          </div>

          {/* Review 3 */}
          <div className="bg-white rounded-[24px] border border-[#E5E7EB] p-7 shadow-sm space-y-5 flex flex-col justify-between">
            <div className="space-y-3">
              <div className="flex text-amber-400 gap-1">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className="w-4 h-4 fill-amber-400" />
                ))}
              </div>
              <p className="text-xs sm:text-sm text-[#111111] leading-relaxed italic">
                &ldquo;We deployed EasiaLearn across all three 10th standard sections. Our school overall average
                improved by 14.2%, and students showed remarkable discipline with the daily streak system.&rdquo;
              </p>
            </div>

            <div className="flex items-center gap-3 pt-3 border-t border-slate-100">
              <div className="w-10 h-10 rounded-full bg-purple-50 text-purple-700 font-bold text-sm flex items-center justify-center">
                KH
              </div>
              <div>
                <h4 className="text-sm font-bold text-[#111111]">Dr. K. Hegde</h4>
                <p className="text-[11px] text-[#475569]">Principal • Karnataka Model High School</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 8 — FREQUENTLY ASKED QUESTIONS (FAQ ACCORDION) */}
      {/* ============================================================ */}
      <section className="py-20 bg-white border-y border-[#E5E7EB]">
        <div className="max-w-[840px] mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center space-y-3 mb-12">
            <span className="text-xs uppercase tracking-widest font-bold text-[#2952CC]">Got Questions?</span>
            <h2 className="text-3xl sm:text-4xl font-extrabold text-[#111111]">Frequently Asked Questions</h2>
            <p className="text-sm text-[#475569]">
              Everything you need to know about EasiaLearn, the AI Tutor, and board exam preparation.
            </p>
          </div>

          <div className="space-y-3">
            {faqs.map((faq, idx) => {
              const isOpen = activeFaq === idx;
              return (
                <div
                  key={idx}
                  className="rounded-2xl border border-[#E5E7EB] bg-[#F8FAFC] overflow-hidden transition-colors"
                >
                  <button
                    onClick={() => setActiveFaq(isOpen ? null : idx)}
                    className="w-full text-left px-5 py-4 flex items-center justify-between gap-4 font-bold text-sm sm:text-base text-[#111111] hover:text-[#2952CC] transition-colors"
                  >
                    <span>{faq.q}</span>
                    <ChevronDown
                      className={`w-5 h-5 text-slate-400 shrink-0 transition-transform duration-200 ${
                        isOpen ? 'rotate-180 text-[#2952CC]' : ''
                      }`}
                    />
                  </button>

                  <AnimatePresence>
                    {isOpen && (
                      <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: 'auto', opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.2 }}
                      >
                        <div className="px-5 pb-5 pt-1 text-xs sm:text-sm text-[#475569] leading-relaxed border-t border-slate-200/60">
                          {faq.a}
                        </div>
                      </motion.div>
                    )}
                  </AnimatePresence>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* SECTION 9 — FINAL CALL TO ACTION (CTA BANNER) */}
      {/* ============================================================ */}
      <section className="py-20 px-4 sm:px-6 lg:px-8 max-w-[1280px] mx-auto">
        <div className="bg-gradient-to-r from-[#2952CC] via-[#3563EB] to-[#4F7DF3] rounded-[32px] p-8 sm:p-14 text-white text-center space-y-6 shadow-2xl shadow-blue-600/20 relative overflow-hidden">
          {/* Subtle Decorative Elements */}
          <div className="absolute top-0 right-0 -mr-16 -mt-16 w-64 h-64 rounded-full bg-white/10 blur-2xl pointer-events-none" />
          <div className="absolute bottom-0 left-0 -ml-16 -mb-16 w-64 h-64 rounded-full bg-blue-900/20 blur-2xl pointer-events-none" />

          <div className="max-w-2xl mx-auto space-y-4 relative z-10">
            <span className="px-3.5 py-1 rounded-full bg-white/20 text-xs font-bold uppercase tracking-wider text-blue-100">
              Start Today for Free
            </span>

            <h2 className="text-3xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight leading-tight">
              Ready to Score Higher in Your Board Exams?
            </h2>

            <p className="text-sm sm:text-base text-blue-100 leading-relaxed max-w-xl mx-auto">
              Join over 50,000+ ambitious students across Karnataka who study smarter with EasiaLearn.
              Zero risk, 100% free starter access.
            </p>

            <div className="pt-4 flex flex-col sm:flex-row items-center justify-center gap-4">
              <button
                id="cta-create-account-btn"
                onClick={() => openAuthModal('signup')}
                className="w-full sm:w-auto px-8 py-4 rounded-2xl bg-white text-[#2952CC] font-bold text-sm sm:text-base hover:bg-slate-100 transition-all shadow-lg active:scale-95"
              >
                Create Free Account
              </button>
              <button
                id="cta-demo-btn"
                onClick={() => setIsAiTutorOpen(true)}
                className="w-full sm:w-auto px-7 py-4 rounded-2xl bg-white/10 border border-white/20 text-white font-semibold text-sm sm:text-base hover:bg-white/20 transition-all"
              >
                Try AI Tutor Demo
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/* 4-COLUMN FOOTER */}
      {/* ============================================================ */}
      <footer className="bg-white border-t border-[#E5E7EB] pt-14 pb-10 px-4 sm:px-6 lg:px-8">
        <div className="max-w-[1280px] mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-10">
          {/* Column 1: Brand Info */}
          <div className="lg:col-span-2 space-y-4 text-left">
            <div className="flex items-center gap-2.5">
              <div className="w-8 h-8 rounded-xl bg-[#2952CC] flex items-center justify-center text-white font-bold text-sm shadow-xs">
                EA
              </div>
              <span className="font-bold text-lg text-[#111111] tracking-tight">EasiaLearn</span>
            </div>
            <p className="text-xs sm:text-sm text-[#475569] max-w-sm leading-relaxed">
              India&apos;s smart EdTech SaaS platform empowering state board students with 24/7 AI tutoring, CBT
              examinations, predictive analytics, and verified achievement credentials.
            </p>
            <div className="text-xs text-[#475569]">
              Proudly aligned with Karnataka KSEAB, NCERT & National Curricula.
            </div>
          </div>

          {/* Column 2: Subjects */}
          <div className="space-y-3 text-left">
            <h4 className="font-bold text-xs uppercase tracking-wider text-[#111111]">Curriculum</h4>
            <ul className="space-y-2 text-xs text-[#475569]">
              <li>
                <button
                  onClick={() => {
                    setSelectedSubject(subjects[0]);
                    setCurrentView('subject_detail');
                  }}
                  className="hover:text-[#2952CC] transition-colors"
                >
                  Mathematics (10th SSLC)
                </button>
              </li>
              <li>
                <button
                  onClick={() => {
                    setSelectedSubject(subjects[1]);
                    setCurrentView('subject_detail');
                  }}
                  className="hover:text-[#2952CC] transition-colors"
                >
                  Science (Physics & Chem)
                </button>
              </li>
              <li>
                <button
                  onClick={() => {
                    setSelectedSubject(subjects[2]);
                    setCurrentView('subject_detail');
                  }}
                  className="hover:text-[#2952CC] transition-colors"
                >
                  Kannada (ಪ್ರಥಮ ಭಾಷೆ)
                </button>
              </li>
              <li>
                <button
                  onClick={() => {
                    setSelectedSubject(subjects[4]);
                    setCurrentView('subject_detail');
                  }}
                  className="hover:text-[#2952CC] transition-colors"
                >
                  Social Sciences
                </button>
              </li>
              <li>
                <button
                  onClick={() => {
                    setSelectedSubject(subjects[5]);
                    setCurrentView('subject_detail');
                  }}
                  className="hover:text-[#2952CC] transition-colors"
                >
                  English Language
                </button>
              </li>
            </ul>
          </div>

          {/* Column 3: Platform */}
          <div className="space-y-3 text-left">
            <h4 className="font-bold text-xs uppercase tracking-wider text-[#111111]">Platform Features</h4>
            <ul className="space-y-2 text-xs text-[#475569]">
              <li>
                <button onClick={() => setIsAiTutorOpen(true)} className="hover:text-[#2952CC] transition-colors">
                  AI Tutor Pro
                </button>
              </li>
              <li>
                <button onClick={() => startMockTest()} className="hover:text-[#2952CC] transition-colors">
                  CBT Mock Examinations
                </button>
              </li>
              <li>
                <button
                  onClick={() => {
                    setCurrentView('student_dashboard');
                    setStudentTab('analytics');
                  }}
                  className="hover:text-[#2952CC] transition-colors"
                >
                  Score Predictor
                </button>
              </li>
              <li>
                <button
                  onClick={() => {
                    setCurrentView('student_dashboard');
                    setStudentTab('flashcards');
                  }}
                  className="hover:text-[#2952CC] transition-colors"
                >
                  Revision Flashcards
                </button>
              </li>
              <li>
                <button onClick={() => setIsProModalOpen(true)} className="hover:text-[#2952CC] transition-colors">
                  Pro Membership
                </button>
              </li>
            </ul>
          </div>

          {/* Column 4: Institutional & Legal */}
          <div className="space-y-3 text-left">
            <h4 className="font-bold text-xs uppercase tracking-wider text-[#111111]">Institutions & Legal</h4>
            <ul className="space-y-2 text-xs text-[#475569]">
              <li>
                <button onClick={() => setCurrentView('institution')} className="hover:text-[#2952CC] transition-colors">
                  School & College Portal
                </button>
              </li>
              <li>
                <button onClick={() => setCurrentView('teacher_portal')} className="hover:text-[#2952CC] transition-colors">
                  Teacher Portal
                </button>
              </li>
              <li>
                <span className="hover:text-[#2952CC] cursor-pointer">Privacy Policy</span>
              </li>
              <li>
                <span className="hover:text-[#2952CC] cursor-pointer">Terms of Service</span>
              </li>
              <li>
                <span className="hover:text-[#2952CC] cursor-pointer">Academic Honor Code</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="max-w-[1280px] mx-auto mt-12 pt-6 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between text-xs text-[#475569] gap-3">
          <p>© 2026 EasiaLearn EdTech Pvt. Ltd. All rights reserved.</p>
          <p>Crafted for Karnataka Board, SSLC & State Curricula.</p>
        </div>
      </footer>
    </div>
  );
};
